apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opsera-claritywithai-0209-dev
resources:
  - ../../base
images:
  - name: PLACEHOLDER_ECR_URI
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/claritywithai-0209
    newTag: dev-5a45eb96-20260209231414
replicas:
  - name: claritywithai-0209
    count: 1
