apiVersion: v1
kind: Service
metadata:
  name: cwa-test-4
  labels:
    app: cwa-test-4
    tenant: opsera
    managed-by: opsera-c2c
spec:
  type: ClusterIP
  selector:
    app: cwa-test-4
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
