apiVersion: v1
kind: Service
metadata:
  name: clarity-1
  labels:
    app: clarity-1
    tenant: opsera
spec:
  selector:
    app: clarity-1
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
