apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-clarity-withai-2020-eaa74-dev

resources:
  - ../../base
  - namespace.yaml
  - deployment.yaml

labels:
  - includeSelectors: false
    pairs:
      app: clarity-withai-2020-eaa74
      environment: dev
      tenant: opsera

images:
  - name: clarity-withai-2020-eaa74
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/clarity-withai-2020-eaa74
    newTag: placeholder
