apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opsera-cwa-test-4-dev
  namespace: argocd
  labels:
    app: cwa-test-4
    tenant: opsera
    environment: dev
    managed-by: opsera-c2c
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Opsera-Test/clarity-withai.git
    targetRevision: main
    path: .opsera-cwa-test-4/k8s/overlays/dev
  destination:
    name: opsera-usw2-np
    namespace: opsera-cwa-test-4-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
