apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cwa-test-2
  labels:
    app: cwa-test-2
    tenant: opsera
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: cwa-test-2-dev.agent.opsera.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cwa-test-2
                port:
                  number: 80
