apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-clarity-1-dev

resources:
  - ../../base
  - namespace.yaml
  - deployment.yaml
  - ingress.yaml

images:
  - name: clarity-1
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/clarity-1
    newTag: dev-e6baf24a-20260228001015
