apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-cwa-test-3-dev

resources:
  - namespace.yaml
  - ../../base

commonLabels:
  environment: dev
  tenant: opsera

images:
  - name: PLACEHOLDER_ECR_URI
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/cwa-test-3
    newTag: a875e02-20260225180735
