apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-cwa-0213-dev

resources:
  - ../../base
  - namespace.yaml
  - deployment.yaml

labels:
  - includeSelectors: false
    pairs:
      app: cwa-0213
      environment: dev
      tenant: opsera

images:
  - name: cwa-0213
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/cwa-0213
    newTag: dev-08006aba-20260213214427
