apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-clarity-1-staging

resources:
  - ../../base
  - namespace.yaml
  - rollout.yaml
  - ingress.yaml
  - service-preview.yaml

images:
  - name: clarity-1
    newName: PLACEHOLDER_ECR_URI
    newTag: v1.0.0
