apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-cwa-test-1-dev

resources:
  - namespace.yaml
  - ../../base

labels:
  - includeSelectors: false
    pairs:
      environment: dev
      tenant: opsera

images:
  - name: PLACEHOLDER_ECR_URI
    newName: PLACEHOLDER_ECR_URI
    newTag: v1.0.0
